name:                dnsflare
version:             0.1.0.0
github:              "montycarlo/dnsflare"
license:             BSD3
author:              "Josh Brown"
maintainer:          "example@example.com"
copyright:           "2021 ROPWARE"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/dnsflare#readme>

dependencies:
- base >= 4.7 && < 5
- network
- bytestring
- iproute
- hourglass
- dns
- req
- aeson
- modern-uri
- text
- async
- time
- cmdargs

library:
  source-dirs: src

executables:
  dnsflare:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -static
      # - -optl-static
      # cc-options: -static
      # ld-options: -static -pthread
    dependencies:
    - dnsflare

tests:
  dnsflare-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dnsflare
